version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 80:3000
      - 5173:5173
    volumes:
      - tv-images:/app/images

  calendar:
    build:
      context: ./calendar
      dockerfile: Dockerfile
    volumes:
      - tv-images:/app/images

volumes:
  tv-images: