version: '3'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    volumes:
      - ./data/images:/app/images
      - ./client/src:/app/src
      - ./client/static:/app/static
      - ./client/svelte.config.js:/app/svelte.config.js
      - ./client/tsconfig.json:/app/tsconfig.json
      - ./client/vite.config.ts:/app/vite.config.ts
      - ./client/tailwind.config.cjs:/app/tailwind.config.cjs
      - ./client/postcss.config.cjs:/app/postcss.config.cjs
      - ./client/.prettierrc:/app/.prettierrc
      - ./client/.prettierignore:/app/.prettierignore
      - ./client/.eslintrc.cjs:/app/.eslintrc.cjs
      - ./client/.eslintignore:/app/.eslintignore
      - ./client/node_modules:/app/node_modules
    ports:
      - 5173:5173
    command: npm run dev -- --host 0.0.0.0 
    labels:
      # Enable Traefik
      - traefik.enable=true
      - traefik.http.services.client.loadbalancer.server.port=5173
      # Enable HTTP
      - traefik.http.routers.client_http.entrypoints=http
      - traefik.http.routers.client_http.rule=PathPrefix(`/`)
      - traefik.http.routers.client_http.service=client
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXTAUTH_URL=http://localhost/
      - NEXTAUTH_URL_INTERNAL=http://localhost/
      - REDIS_PASSWORD=${REDIS_PASSWORD}

  calendar:
    build:
      context: ./calendar
      dockerfile: Dockerfile
    volumes:
      - ./data/images:/app/images
    environment:
      - CALENDAR_URL=${CALENDAR_URL}

  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ./data/redis:/data
    command: redis-server --save 60 1 --appendonly yes --requirepass ${REDIS_PASSWORD}

  traefik:
    image: traefik:latest
    restart: always
    command:
      - --entrypoints.http.address=:80
      - --providers.docker=true
      - --api.insecure=true
    labels:
      # Make the Traefik dashboard available at http://traefik.${DOMAIN}
      - traefik.http.routers.traefik.rule=Host(`traefik.${DOMAIN}`)
      - traefik.http.routers.traefik.entrypoints=http
      - traefik.http.routers.traefik.service=api@internal
    ports:
      - 80:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro