name: Calendar Generator Checks
defaults:
  run:
    working-directory: calendar
on:
  push:
  pull_request:
  workflow_dispatch:
env:
  GOPATH: ${{ github.workspace }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Vet
        run: go vet .
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.20
      - name: Install golint
        run: go get -u golang.org/x/lint/golint
      - name: Run golint
        run: golint .
