name: Client Checks
defaults:
  run:
    working-directory: client
on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Node modules
        run: npm ci
      - name: Run linters
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    env:
      GOOGLE_CLIENT_ID: "action_client_id" 
      GOOGLE_CLIENT_SECRET: "action_client_secret"
      AUTH_SECRET: "action_auth_secret"
      NEXTAUTH_URL: "action_nextauth_url"
      USER_WHITELIST: "action_user_whitelist"
      REDIS_PASSWORD: "client_redis_password"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Node modules
        run: npm ci
      - name: Build
        run: npm run build
